#!/usr/bin/env python3
"""Shiori's Haiku icon: the mark of scripts/generate-shiori-icons.py (a blue
bookmark ribbon under a gold lens) as an HVIF vector icon, written to
haiku/Icon.rdef. HVIF (Haiku's flat icon format): "ncif", then styles,
paths and shapes on a 64 x 64 canvas. Run from the repository's root:

    python3 haiku/tools/icon.py            (writes haiku/Icon.rdef)
    python3 haiku/tools/icon.py --check    (exit 1 when it differs)
"""
import math
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "Icon.rdef")

# Style types, path and shape flags (src/libs/icon/flat_icon/FlatIconFormat.h).
STYLE_SOLID = 1          # RGBA
PATH_CLOSED = 1 << 1
PATH_NO_CURVES = 1 << 3
SHAPE_PATH_SOURCE = 10
SHAPE_HAS_TRANSFORMERS = 1 << 4
TRANSFORMER_STROKE = 23
CAP_ROUND, JOIN_ROUND = 2, 2


def coord(v):
    """One coordinate: a byte for whole numbers in -32..95, else two (1/102 steps from -128)."""
    if float(v).is_integer() and -32 <= v <= 95:
        return bytes([int(v) + 32])
    n = int(round((v + 128.0) * 102.0))
    assert 0 <= n < 1 << 15, v
    return bytes([(n >> 8) | 0x80, n & 0xFF])


def polygon(points):
    out = bytes([PATH_CLOSED | PATH_NO_CURVES, len(points)])
    for x, y in points:
        out += coord(x) + coord(y)
    return out


def circle(cx, cy, r):
    """A circle as four curved points: x, y, then the in and out control points."""
    k = r * 0.5523
    pts = [((cx, cy - r), (cx - k, cy - r), (cx + k, cy - r)),
           ((cx + r, cy), (cx + r, cy - k), (cx + r, cy + k)),
           ((cx, cy + r), (cx + k, cy + r), (cx - k, cy + r)),
           ((cx - r, cy), (cx - r, cy + k), (cx - r, cy - k))]
    out = bytes([PATH_CLOSED, len(pts)])
    for p, i, o in pts:
        out += coord(p[0]) + coord(p[1]) + coord(i[0]) + coord(i[1]) + coord(o[0]) + coord(o[1])
    return out


def line(a, b):
    return bytes([PATH_NO_CURVES, 2]) + coord(a[0]) + coord(a[1]) + coord(b[0]) + coord(b[1])


def shape(style, path, stroke=None):
    out = bytes([SHAPE_PATH_SOURCE, style, 1, path])
    if stroke is None:
        return out + bytes([0])
    # A stroke: its width + 128, the join (low nibble) and cap (high), the miter limit.
    return out + bytes([SHAPE_HAS_TRANSFORMERS, 1, TRANSFORMER_STROKE, int(stroke) + 128,
                        (CAP_ROUND << 4) | JOIN_ROUND, 4])


def icon():
    # The mark's proportions (generate-shiori-icons.py's RIBBON and LENS), on 64 units.
    # Wide and bold enough to read at 16 px in the Deskbar and Tracker's
    # lists: a broad ribbon with a dark edge, and a big lens whose gold ring
    # and handle sit on a dark edge too, so they hold on any panel.
    ribbon = [(9, 3), (37, 3), (37, 49), (23, 38), (9, 49)]
    cx, cy, r = 38, 36, 15
    a = math.radians(45)
    h0 = (cx + r * math.cos(a), cy + r * math.sin(a))
    h1 = (h0[0] + 9, h0[1] + 9)
    styles = [
        (122, 162, 247, 255),  # 0 the ribbon (Tokyo Night blue)
        (26, 27, 38, 255),     # 1 the dark edge (the tile's navy)
        (255, 255, 255, 110),  # 2 the glass's sheen
        (232, 182, 104, 255),  # 3 the lens's gold
    ]
    paths = [polygon(ribbon), circle(cx, cy, r), line(h0, h1)]
    shapes = [
        shape(0, 0),
        shape(1, 0, stroke=2),
        shape(2, 1),
        shape(1, 2, stroke=10),   # the handle's dark edge
        shape(3, 2, stroke=6),    # the handle
        shape(1, 1, stroke=7),    # the ring's dark edge
        shape(3, 1, stroke=4),    # the ring
    ]
    out = b"ncif" + bytes([len(styles)])
    for rgba in styles:
        out += bytes([STYLE_SOLID]) + bytes(rgba)
    out += bytes([len(paths)]) + b"".join(paths)
    out += bytes([len(shapes)]) + b"".join(shapes)
    return out


def rdef(data):
    hexed = data.hex().upper()
    lines = [hexed[i:i + 64] for i in range(0, len(hexed), 64)]
    body = "\n".join(f'\t$"{line}"' for line in lines)
    return ("// Generated by haiku/tools/icon.py (Shiori's mark as an HVIF vector icon): don't edit.\n\n"
            f"resource vector_icon {{\n{body}\n}};\n")


if __name__ == "__main__":
    text = rdef(icon())
    if "--check" in sys.argv:
        with open(OUT) as f:
            sys.exit(0 if f.read() == text else 1)
    with open(OUT, "w") as f:
        f.write(text)
    print(f"wrote {OUT} ({len(icon())} bytes of HVIF)")
