#!/bin/sh
# Writes the app_version resource from Shiori's one version (project.yml's
# MARKETING_VERSION), so Tracker's Get Info and the app agree with every
# other Shiori. Run by the Makefile: tools/version-rdef.sh > Version.rdef
version=$(sed -n 's/.*MARKETING_VERSION: *"\{0,1\}\([0-9][0-9.]*\).*/\1/p' "$(dirname "$0")/../../project.yml" | head -1)
[ -n "$version" ] || version=0.0.0
IFS=. read -r major middle minor <<EOV
$version
EOV
cat <<EOR
// Generated by haiku/tools/version-rdef.sh from project.yml: don't edit.
resource app_version {
	major  = ${major:-0},
	middle = ${middle:-0},
	minor  = ${minor:-0},
	variety = B_APPV_FINAL,
	internal = 0,
	short_info = "Shiori $version",
	long_info = "Shiori for Haiku $version: search Hister and Kura (Machiya)."
};
EOR
