// Writes tests/vectors.inc: search-core.js's own answers for the inputs
// below, so the C++ twins are checked against the JavaScript itself.
// Run from the shiori repo root after search-core changes:
//
//   node haiku/tests/gen-vectors.mjs patches/shiori/search-core.js > haiku/tests/vectors.inc
//   node haiku/tests/gen-vectors.mjs --c patches/shiori/search-core.js > classic/tests/vectors.h
//
// --c writes the same vectors for Shiori for Classic Macintosh's C89 core:
// a plain struct, and string literals with every byte outside printable
// ASCII as an octal escape (C89 has no \u, and a raw byte is the compiler's
// business).
import { readFileSync } from 'node:fs';
import vm from 'node:vm';

const args = process.argv.slice(2);
const cMode = args.includes('--c');
const file = args.find((a) => a !== '--c') || 'patches/shiori/search-core.js';
const context = { URL, URLSearchParams, TextEncoder, TextDecoder, console };
context.globalThis = context;
vm.createContext(context);
vm.runInContext(readFileSync(file, 'utf8'), context);
const S = context.ShioriSearch;

const inputs = [
  '', ' ', '*', 'a', 'hist', 'hist ', 'raspberry pi', 'raspberry pi ', 'pi 5', 'hist*', 'label:alpha', 'c++',
  '"exact phrase', '"exact" phrase', '@vintage', '町家', '町家 の', 'café', 'naïve résumé', 'x -label:vault -metadata.source:vault',
  'raspberry "pi', '"raspberry pi" zero', '"', 'shiori label:vault', 'title:shio* tag:area/projects', '* label:vault',
  'rust label:programming async', 'label:(alpha|mac) added:>2026-01-01', '-domain:www.example.com go', 'site:example.com go',
  '@vintage amiga', 'rust -domain:reddit.com', 'metadata.code_kind:issue bug', 'type:local pi', 'a1', '12', 'x2',
  'hello—world', 'emoji 😀', '  padded  words  ', 'tab\there', 'Ünïcödé', 'привет мир', 'ab',
];

// A C89 string literal: printable ASCII as is (but \\, " and ?, which could
// make a trigraph), everything else as three-digit octal escapes of its UTF-8 bytes.
const cString = (s) => '"' + [...Buffer.from(s, 'utf8')].map((b) => (b >= 0x20 && b < 0x7f && b !== 0x22 && b !== 0x5c && b !== 0x3f)
  ? String.fromCharCode(b) : '\\' + b.toString(8).padStart(3, '0')).join('') + '"';
const q = cMode ? cString : (s) => JSON.stringify(s);
const out = [];
if (cMode) {
  out.push('/* Generated by haiku/tests/gen-vectors.mjs --c from search-core.js. Do not edit. */');
  out.push('struct Vec { const char *fn; const char *in; const char *want; };');
  out.push('static const struct Vec kVectors[] = {');
} else {
  out.push('// Generated by tests/gen-vectors.mjs from search-core.js. Do not edit.');
  out.push('struct Vec { const char* fn; const char* in; const char* want; };');
  out.push('static const Vec kVectors[] = {');
}
for (const s of inputs) {
  out.push(`  {"prefixLastWord", ${q(s)}, ${q(S.prefixLastWord(s))}},`);
  out.push(`  {"prefixLastWordUnion", ${q(s)}, ${q(S.prefixLastWord(s, { union: true }))}},`);
  out.push(`  {"histerText", ${q(s)}, ${q(S.histerText(s))}},`);
  out.push(`  {"codeHisterText", ${q(s)}, ${q(S.histerText(S.codeQuery(s)))}},`);
  out.push(`  {"filesHisterText", ${q(s)}, ${q(S.histerText(S.filesQuery(s)))}},`);
  out.push(`  {"webQuery", ${q(s)}, ${q(S.webQuery(s))}},`);
  out.push(`  {"kuraQuery", ${q(s)}, ${q(S.kuraQuery(s))}},`);
  out.push(`  {"kuraURL", ${q(s)}, ${q(S.kuraURL('https://kura.example/', s, { limit: 5 }))}},`);
  // The Notes pill's next page, over every vault.
  out.push(`  {"kuraURLVault", ${q(s)}, ${q(S.kuraURL('https://kura.example/', s, { limit: 30, offset: 30, vault: 'all' }))}},`);
  // HisterClient.search's request, as the Linux client builds it (URLSearchParams + JSON.stringify).
  // No words: the newest pages ("*" sorted by date, Hister's "recent"), as the Library's "*".
  const newest = !s.trim();
  const hister = `https://h.example/search?${new URLSearchParams({ query: JSON.stringify({ text: S.histerText(newest ? '*' : s), highlight: 'HTML', limit: 30, ...(newest ? { sort: 'date' } : {}) }) })}`;
  out.push(`  {"histerSearchURL", ${q(s)}, ${q(hister)}},`);
}
out.push('};');
console.log(out.join('\n'));
