// Writes tests/vectors.inc: search-core.js's own answers for the inputs
// below, so the C++ twins are checked against the JavaScript itself.
// Run from the shiori repo root after search-core changes:
//
//   node haiku/tests/gen-vectors.mjs patches/shiori/search-core.js > haiku/tests/vectors.inc
import { readFileSync } from 'node:fs';
import vm from 'node:vm';

const file = process.argv[2] || 'patches/shiori/search-core.js';
const context = { URL, URLSearchParams, TextEncoder, TextDecoder, console };
context.globalThis = context;
vm.createContext(context);
vm.runInContext(readFileSync(file, 'utf8'), context);
const S = context.ShioriSearch;

const inputs = [
  '', ' ', '*', 'a', 'hist', 'hist ', 'raspberry pi', 'raspberry pi ', 'pi 5', 'hist*', 'label:alpha', 'c++',
  '"exact phrase', '"exact" phrase', '@vintage', '町家', '町家 の', 'café', 'naïve résumé', 'x -label:vault -metadata.source:vault',
  'raspberry "pi', '"raspberry pi" zero', '"', 'shiori label:vault', 'title:shio* tag:area/projects', '* label:vault',
  'rust label:programming async', 'label:(alpha|mac) added:>2026-01-01', '-domain:www.example.com go', 'site:example.com go',
  '@vintage amiga', 'rust -domain:reddit.com', 'metadata.code_kind:issue bug', 'type:local pi', 'a1', '12', 'x2',
  'hello—world', 'emoji 😀', '  padded  words  ', 'tab\there', 'Ünïcödé', 'привет мир', 'ab',
];

const q = (s) => JSON.stringify(s);
const out = [];
out.push('// Generated by tests/gen-vectors.mjs from search-core.js. Do not edit.');
out.push('struct Vec { const char* fn; const char* in; const char* want; };');
out.push('static const Vec kVectors[] = {');
for (const s of inputs) {
  out.push(`  {"prefixLastWord", ${q(s)}, ${q(S.prefixLastWord(s))}},`);
  out.push(`  {"prefixLastWordUnion", ${q(s)}, ${q(S.prefixLastWord(s, { union: true }))}},`);
  out.push(`  {"histerText", ${q(s)}, ${q(S.histerText(s))}},`);
  out.push(`  {"codeHisterText", ${q(s)}, ${q(S.histerText(S.codeQuery(s)))}},`);
  out.push(`  {"filesHisterText", ${q(s)}, ${q(S.histerText(S.filesQuery(s)))}},`);
  out.push(`  {"webQuery", ${q(s)}, ${q(S.webQuery(s))}},`);
  out.push(`  {"kuraQuery", ${q(s)}, ${q(S.kuraQuery(s))}},`);
  out.push(`  {"kuraURL", ${q(s)}, ${q(S.kuraURL('https://kura.example/', s, { limit: 5 }))}},`);
  // The Notes pill's next page, over every vault.
  out.push(`  {"kuraURLVault", ${q(s)}, ${q(S.kuraURL('https://kura.example/', s, { limit: 30, offset: 30, vault: 'all' }))}},`);
  // HisterClient.search's request, as the Linux client builds it (URLSearchParams + JSON.stringify).
  const hister = `https://h.example/search?${new URLSearchParams({ query: JSON.stringify({ text: S.histerText(s), highlight: 'HTML', limit: 30 }) })}`;
  out.push(`  {"histerSearchURL", ${q(s)}, ${q(hister)}},`);
}
out.push('};');
console.log(out.join('\n'));
